default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 1dc9eb131c2ea4816c708e4d85820d2cc8542683 # frozen: v0.5.0
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes", "--exit-non-zero-on-fix"]
        exclude: baselayer|node_modules|static|data
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0 # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        pass_filenames: true
        exclude: baselayer|node_modules|doc|data|^(.*_template\.html)$
        args: [--prose-wrap=preserve]
  - repo: local
    hooks:
      - id: ESLint
        name: ESLint
        entry: npx eslint -c eslint.config.js --fix
        language: system
        files: static/.*\.jsx?$|static/.*\.js$
        types: [file]
